### ISSUE TITLE
Make the userscript contain the information for an entry point not the main.json

### ISSUE THREAD

**Issue by RJ-Infinity** [RJ-Infinity/ThisCord#13]

**Comment by titushm** [comment]
can we not use the webserver to get a list of scripts in the scrips dir

**Comment by RJ-Infinity** [comment]
we already do that
the issue is that only some of these want to be run most only want to be run when they are `using`ed

**Comment by titushm** [comment]
well thats why we should put apis in a seperate folder

**Comment by RJ-Infinity** [comment]
but then what if somthing can be `using`ed and wants to be run on startup

**Comment by RJ-Infinity** [comment]
we can organise apis in a seperate folder but it shouldnt be used for anything more than orginisiation

ThisCord shouldnt determine how to run them based of where they are located
