### ISSUE TITLE
merge ImageModal into the graphics library

### ISSUE THREAD

**Issue by RJ-Infinity** [RJ-Infinity/ThisCord#27]
(reported by snitch)

**Comment by RJ-Infinity** [comment]
this was created before the graphics library was a thing and now it is it probabably wants to be integrated into it

**Comment by RJ-Infinity** [comment]
also could we make the graphics library a folder with many components in it?

**Comment by titushm** [comment]
> also could we make the graphics library a folder with many components in it?

no

thats stupid
