### ISSUE TITLE
allow exports function to use single varibles

### ISSUE THREAD

**Issue by titushm** [RJ-Infinity/ThisCord#5]
![image](https://github.com/RJ-Infinity/ThisCord/assets/86983072/8be60909-a234-4147-96d5-c07f25fa0b4e)
like this

**Comment by RJ-Infinity** [comment]
i think that having a function that is somthing like `exportUnique` would be better as then you can use both systems

**Comment by titushm** [comment]
maybe `singleExport` would be better

**Comment by titushm** [comment]
wait why are we doing this

**Comment by RJ-Infinity** [comment]
so that you can either export an object and have it merged with all the others or just export a single object which could only be called once per class

**Comment by RJ-Infinity** [comment]
> maybe `singleExport` would be better

this dosent emphasise the fact that it can only be called once per module though

**Comment by titushm** [comment]
`singleCanOnlyBeCalledOncePerModuleExport`

**Comment by RJ-Infinity** [comment]
it can only be called oncebeacuse in the old system if you did ```js
exports({
	ParseContent,
	resolveMentions,
	resolveChannelMentions,
});
exports({
	resolveRoleMentions,
	resolveRelativeTime,
	Sanitise
});
``` all the objects would be exported however with the new system as a single object is being exported it couldnt support two calls as then you would have to remove the previous export so it wwould be better if this creates an error

**Comment by titushm** [comment]
nice formatting

**Comment by RJ-Infinity** [comment]
i think `exportSingle` is better than `singleExport` as it fits in with `exportAs` better

**Comment by titushm** [comment]
Fixed in #6
